# Numpy Notes and Practice

The most important object defined in NumPy is an N-dimensional array type called ndarray. It describes the collection of items of the same type. Items in the collection can be accessed using a zero-based index.

Every item in an ndarray takes the same size of block in the memory. Each element in ndarray is an object of data-type object (called dtype).

numpy.array(object, dtype = None, copy = True, order = None, subok = False, ndmin = 0)

In [1]:
import numpy as np

In [2]:
a = np.array([10,20,30,40])

In [3]:
a

array([10, 20, 30, 40])

We can add dimensions using ndmin

In [4]:
b = np.array([10,20,30,40],ndmin=2)

In [5]:
b

array([[10, 20, 30, 40]])

We can add data types:

    1)complex
    
    2)C - matrix is read from coloum to row (row-major order)
    
    3)F - FOrtran type , matrix is read from row to col (column-major order)

In [6]:
c = np.array([1, 2, 3], dtype = complex) 

In [7]:
c

array([1.+0.j, 2.+0.j, 3.+0.j])

A dtype object is constructed using the following syntax −

numpy.dtype(object, align, copy)

The parameters are −

Object − To be converted to data type object

Align − If true, adds padding to the field to make it similar to C-struct

Copy − Makes a new copy of dtype object. If false, the result is reference to builtin data type object

In [8]:
b.shape

(1, 4)

In [9]:
b.ndim

2

In [10]:
b.dtype.name

'int32'

In [11]:
b.size  #no. of items

4

In [12]:
b.itemsize  #size of dtype(int32)

4

In [13]:
type(b)

numpy.ndarray

The function zeros creates an array full of zeros, the function ones creates an array full of ones, and the function empty creates an array whose initial content is random and depends on the state of the memory. By default, the dtype of the created array is float64.

In [14]:
np.zeros( (3,4) )

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
np.ones( (2,3,4), dtype=np.int16 ) 

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [16]:
np.empty( (3,4) )

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
#we can add a constant 
print(b)
print(b+10)

[[10 20 30 40]]
[[20 30 40 50]]


You can also pass a list of lists to create a matrix like a 2d array.

In [18]:
list2 = [[0,1,2], [3,4,5], [6,7,8]]
arr2d = np.array(list2)
arr2d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

You may also specify the datatype by setting the dtype argument. Some of the most commonly used numpy dtypes are: 'float', 'int', 'bool', 'str' and 'object'.

To control the memory allocations you may choose to use one of ‘float32’, ‘float64’, ‘int8’, ‘int16’ or ‘int32’.

In [19]:
# Create a float 2d array
arr2d_f = np.array(list2, dtype='float')
arr2d_f

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

You can also convert it to a different datatype using the astype method.

In [20]:
# Convert to 'int' datatype
arr2d_f.astype('int')

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [21]:
arr2d_f.astype('int').astype('str')

array([['0', '1', '2'],
       ['3', '4', '5'],
       ['6', '7', '8']], dtype='<U11')

In [22]:
# Create a boolean array
arr2d_b=np.array([0,2,3],dtype=bool)
arr2d_b

array([False,  True,  True])

In [23]:
# Create an object array to hold numbers as well as strings
arr1d_obj = np.array([1, 'a'],dtype='object')
arr1d_obj

array([1, 'a'], dtype=object)

Finally, you can always convert an array back to a python list using tolist().



In [24]:
arr1d_obj.tolist()

[1, 'a']

In [25]:
list2 = [[1, 2, 3, 4],[3, 4, 5, 6], [5, 6, 7, 8]]
arr2 = np.array(list2, dtype='int')
print(arr2)

# shape
print('Shape: ', arr2.shape)

# dtype
print('Datatype: ', arr2.dtype)

# size
print('Size: ', arr2.size)

# ndim
print('Num Dimensions: ', arr2.ndim)

[[1 2 3 4]
 [3 4 5 6]
 [5 6 7 8]]
Shape:  (3, 4)
Datatype:  int32
Size:  12
Num Dimensions:  2


In [26]:
# Extract the first 2 rows and columns
arr2[:2, :2]

array([[1, 2],
       [3, 4]])

In [27]:
# Get the boolean output by applying the condition to each element.
b = arr2 > 4
b

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [28]:
arr2[b]  #only true values will get displayed

array([5, 6, 5, 6, 7, 8])

How to reverse the rows and the whole array?

In [29]:
# Reverse only the row positions
arr2[::-1, ]

array([[5, 6, 7, 8],
       [3, 4, 5, 6],
       [1, 2, 3, 4]])

In [30]:
# Reverse the row and column positions
arr2[::-1, ::-1]

array([[8, 7, 6, 5],
       [6, 5, 4, 3],
       [4, 3, 2, 1]])

How to represent missing values and infinite?
Missing values can be represented using np.nan object, while np.inf represents infinite.

In [31]:
#only works for float values
arr2 = np.array(arr2, dtype='float')
print(arr2)
arr2[1,1] = np.nan  # not a number
arr2[1,2] = np.inf  # infinite
arr2

[[1. 2. 3. 4.]
 [3. 4. 5. 6.]
 [5. 6. 7. 8.]]


array([[ 1.,  2.,  3.,  4.],
       [ 3., nan, inf,  6.],
       [ 5.,  6.,  7.,  8.]])

In [32]:
# Replace nan and inf with -1. Don't use arr2 == np.nan
missing_bool = np.isnan(arr2) | np.isinf(arr2)
print(np.isnan(arr2))

arr2[missing_bool] = -1  
arr2


[[False False False False]
 [False  True False False]
 [False False False False]]


array([[ 1.,  2.,  3.,  4.],
       [ 3., -1., -1.,  6.],
       [ 5.,  6.,  7.,  8.]])

How to compute mean, min, max on the ndarray?

In [33]:
# mean, max and min
print("Mean value is: ", arr2.mean())
print("Max value is: ", arr2.max())
print("Min value is: ", arr2.min())

Mean value is:  3.5833333333333335
Max value is:  8.0
Min value is:  -1.0


In [34]:
# Row wise and column wise min
print("Column wise minimum: ", np.amin(arr2, axis=0))
print("Row wise minimum: ", np.amin(arr2, axis=1))

Column wise minimum:  [ 1. -1. -1.  4.]
Row wise minimum:  [ 1. -1.  5.]


In [35]:
# Cumulative Sum
np.cumsum(arr2)

array([ 1.,  3.,  6., 10., 13., 12., 11., 17., 22., 28., 35., 43.])